### ISSUE TITLE
Support reload on the server restart

### ISSUE THREAD

**Issue by majo44** [dai-shi/easy-livereload#22]
When loading with the SSR when server restarts the browser is not reloading.

**Comment by majo44** [comment]
```
   let disconnected = false;
   document.addEventListener('LiveReloadDisconnect', () => disconnected = true);
   document.addEventListener('LiveReloadConnect', () => disconnected ? LiveReload.performReload({path: ''}) : undefined);
```

**Comment by dai-shi** [comment]
So, does that mean `node-dev` doesn't work well with SSR?
I think your workaround is good. Thanks for sharing.

**Comment by majo44** [comment]
Now works perfectly with the `node-dev`, I had to dig in how `livereload.js` is works but with this small workaround everything works as expected :) Best regards.
