### ISSUE TITLE
Infinite livereload

### ISSUE THREAD

**Issue by amatiash** [dai-shi/easy-livereload#7]
My application has a loop reloading, using this package, when testing on mobile (lan, remote device, via local ip) and chrome debugger opened.

Commented this line and the issue has been resolved.
https://github.com/dai-shi/easy-livereload/blob/996ce2a5fafc7bf85e7e3feff07cb1357afed4b0/index.js#L121

It took me 3h to figure out what was going on.
Please, consider that users might have the same issue, which is caused by this line.

**Comment by dai-shi** [comment]
Thanks for reporting. According to your observation, I would like to make the auto reconnect feature optional. I will make a fix soon.

**Comment by amatiash** [comment]
Thank you very much for the update!

вс, 22 марта 2020 г., 3:55 Daishi Kato <notifications@github.com>:

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/easy-livereload/v/1.4.0

Please reopen this issue if the problem persists.
